"use strict";/*
 * @Author       : HCLonely
 * @Date         : 2024-09-11 15:40:57
 * @LastEditTime : 2025-07-09 20:36:01
 * @LastEditors  : HCLonely
 * @FilePath     : /hexo-bilibili-bangumi/src/lib/templates/index.js
 * @Description  : 前端页面交互脚本，实现标签页切换和分页加载功能。
 *                 包含自定义DOM操作方法、标签页点击事件处理，以及
 *                 通过AJAX异步加载更多数据的分页功能。
 */(function(){function a(){this.classList.add("bangumi-active");let a=this.siblings();for(let b=0;b<a.length;b++)a[b].classList.remove("bangumi-active");// 显示对应板块
const b=this.id.replace("tab","item"),c=document.getElementById(b);c.classList.remove("bangumi-hide"),c.classList.add("bangumi-show"),a=document.getElementById(b).siblings();for(let b=0;b<a.length;b++)a[b].classList.remove("bangumi-show"),a[b].classList.add("bangumi-hide")}Element.prototype.siblings=function(){const a=[],b=this.parentNode.children;for(let c=0;c<b.length;c++)b[c]!==this&&a.push(b[c]);return a};const b=document.getElementsByClassName("bangumi-tab");for(let c=0;c<b.length;c++)b[c].onclick=a,b[c].onclick.apply(b[c]);"undefined"!=typeof hexoBilibiliBangumiOptions.pagenumsPre&&axios.get(new URL("../bangumis.json",window.location.href)).then(a=>{if(a.data){const b={wantWatch:a.data.wantWatch.slice(10).map(a=>hexoBilibiliBangumiOptions.pug.render(hexoBilibiliBangumiOptions.pugTemplate,{item:a,...hexoBilibiliBangumiOptions.pugOptions})).join("\n"),watching:a.data.watching.slice(10).map(a=>hexoBilibiliBangumiOptions.pug.render(hexoBilibiliBangumiOptions.pugTemplate,{item:a,...hexoBilibiliBangumiOptions.pugOptions})).join("\n"),watched:a.data.watched.slice(10).map(a=>hexoBilibiliBangumiOptions.pug.render(hexoBilibiliBangumiOptions.pugTemplate,{item:a,...hexoBilibiliBangumiOptions.pugOptions})).join("\n")};document.querySelectorAll("#bangumi-item1>.bangumi-pagination")[0].insertAdjacentHTML("beforeBegin",b.wantWatch),document.querySelectorAll("#bangumi-item2>.bangumi-pagination")[0].insertAdjacentHTML("beforeBegin",b.watching),document.querySelectorAll("#bangumi-item3>.bangumi-pagination")[0].insertAdjacentHTML("beforeBegin",b.watched)}}),document.getElementsByClassName("bangumi-tab")[hexoBilibiliBangumiOptions.show].click()})();